sudo: false
language: node_js
node_js:
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - 'iojs'
matrix:
  fast_finish: true
os:
  - linux
cache:
  directories:
    - node_modules
    - bower_components
notifications:
  email: false
branches:
  only:
    - master
  except:
    - gh-pages
before_install:
  - npm install
  - bower install
before_script:
  - npm dedupe
  - npm prune
script:
  - npm run clean
  - npm run cover
after_success:
  - 'if [[ $TRAVIS_BRANCH == "master" ]]; then npm run doc; fi'
  - npm run codeclimate
  - npm run semantic-release
