sudo: false
language: node_js
node_js:
  - '4.1'
  - '4.0'
  - '0.12'
  - 'iojs'
matrix:
  fast_finish: true
os:
  - linux
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
  except:
    - gh-pages
before_script:
  - npm dedupe
  - npm prune
script:
  - npm run clean
  - npm run cover
after_script:
  - |

      declare exitCode;
      $(npm bin)/travis-after-all
      exitCode=$?
      if [ $exitCode -eq 0 ]; then
        npm run codeclimate;
        npm run semantic-release;
      fi
